export const REQUEST_TO_TEXT_FASTAPI = 'REQUEST_TO_TEXT_FASTAPI'
export const REQUEST_TO_VL_FASTAPI = 'REQUEST_TO_VL_FASTAPI'
export const SET_RAW_DATA = "SET_RAW_DATA";
export const SET_USER_SESSION = "SET_USER_SESSION";
